kind: pipeline
name: default
type: docker

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: drone-cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./gradle_cache

  - name: build-java
    image: eclipse-temurin:17-jdk
    environment:
      GRADLE_USER_HOME: /drone/src/gradle_cache
      TZ: Europe/London
    commands:
      - chmod +x gradlew
      - ./gradlew test shadowJar

  - name: publish-image-quay
    image: plugins/docker:19.03.8
    settings:
      registry: quay.io
      repo: quay.io/fivium/dmda
      tags:
        - ${DRONE_BRANCH//\//-}-${DRONE_BUILD_NUMBER}
      config:
        from_secret: docker_config_json
    when:
      branch:
        - master
        - master-auto
        - feature/**
      event:
        - push

  - name: publish-image-ecr
    image: plugins/ecr
    settings:
      region: eu-west-2
      registry: 847993322739.dkr.ecr.eu-west-2.amazonaws.com
      repo: fivium-app/dmda
      tags:
        - ${DRONE_BRANCH//\//-}-${DRONE_BUILD_NUMBER}
      access_key: AKIA4K4CXHTZ7KAUZJWL
      secret_key:
        from_secret: aws_secret_key
      config:
        from_secret: docker_config_json # used for pulling image bases when building Dockerfile
    when:
      branch:
        - master
        - master-auto
        - feature/**
      event:
        - push

  - name: publish-helm-chart
    image: quay.io/fivium/drone-helm
    settings:
      chart_name: dmda
      chart_version: 0.${DRONE_BUILD_NUMBER}.0
      app_version: master-auto-${DRONE_BUILD_NUMBER}
    environment:
      AWS_ACCESS_KEY_ID: AKIA4K4CXHTZ7KAUZJWL
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_key
    when:
      branch:
        - master-auto
      event:
        - push

  - name: sync-reports
    image: alpine:3
    commands:
      - mkdir -p /var/webfiles/${DRONE_BUILD_NUMBER}
      - cp -r build/reports /var/webfiles/${DRONE_BUILD_NUMBER}
    volumes:
      - name: webfiles
        path: /var/webfiles
    when:
      status: [ success, failure ]

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: drone-cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./gradle_cache

volumes:
  - name: webfiles
    host:
      path: /home/fivium/www/dmda
  - name: drone-cache
    host:
      path: /home/fivium/drone-cache

---
kind: secret
name: docker_config_json
data: loNAK+ZOklcYdNkcd7BgenwXGNWClEAUf3zTE61dViwpTmxB8oUp6rpsheogqh62NhtcD09cp5/dXd6f+y2+GPZm0pkNKb0zEW2YXniDeFLfnj9rYp+8Zual7gBCjK28jy1sxQJ2qingNnQLeP44UnqkcfmqcW2gxXjbQdeYlcf9/O+mcHfVKemXDl4h+SLZnYuIEi3iS3TYwB/nGN0J73ygzKnLesdN1ewtYyhUbzr6/NfdM7SOUsYIIyQ+B7VIe/BsfB4BKh8Eu4SLPQf9CzPPul0ihUU/U8fVLOv9wbKaafg7+zNIZE6cdbbura4rFiLSBslBceac3S+hdDkRPNJT1iTdNTGr3xW+1jkuZ7xLVFeVIbU=

---
kind: secret
name: aws_secret_key
data: rOhSJ7/HYVXu6ZLnG77zZIeJ12QHs2VXpU5YFPvLUrigOUzuVikrPHJNt1yzzSH2n+vgmrV8dxh2Ky4+vCdOG5SOhX4=