apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.shared.namespace }}
spec:
  secretStoreRef:
    name: secrets-manager
    kind: ClusterSecretStore

  refreshInterval: "1m"

  target:
    name: {{ .Chart.Name }}
    template:
      templateFrom:
        - configMap:
            name: {{ .Chart.Name }}
            items:
              - key: config.xml
              - key:
    creationPolicy: Owner
    deletionPolicy: Delete

  dataFrom:
    - extract:
        key: {{ .Values.global.shared.namespace }}/{{ .Chart.Name }}