apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.shared.namespace }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}